### ISSUE TITLE
Feature request : make the Jitsi Meet server URL a parameter

### ISSUE THREAD

**Issue by MagicFab** [ryanprior/meet#1]
The `https://meet.jit.si` URL is hard-coded in the script.

Making this a configuration parameter while keeping [](https://meet.jit.si) as configurable default would be useful for people that want to generate meeting URLs for other servers (including their own).

**Comment by WhereIsX** [comment]
Available in 1.1.0 (out now!)

Thanks for suggestion @MagicFab

**Comment by MagicFab** [comment]
Awesome implementation, thank YOU !
