### ISSUE TITLE
Raspberry Pi and Crystal.

### ISSUE THREAD

**Issue by hbarnard** [ryanprior/meet#2]
I wanted to use this on a raspberry pi, for setting up meetings on our test servers, but remaining headless:

`Skipping acquire of configured file 'main/binary-armhf/Packages' as repository 'https://dist.crystal-lang.org/apt crystal InRelease' doesn't support architecture 'armhf'`

So there probably isn't any non-fiddly way to compile on the pi. It's already very useful, so thanks!

**Comment by ryanprior** [comment]
I looked at a few resources for building Crystal code for arm and it all looks pretty rough. I might try and build meet for my Pinebook and see how that goes, and a pi build might be similar.

Links I looked at:
- https://pi3g.com/2018/12/21/crystal-alpine-on-the-raspberry-pi/
- https://stackoverflow.com/questions/42796143/how-do-i-install-crystal-lang-on-rapsberry-pi

**Comment by hbarnard** [comment]
Hi Ryan, For me, don't worry and thanks. If a few others turn up, then it might be worth spending some time on...

**Comment by hbarnard** [comment]
http://constxife.ru/blog/2018/10/16/rpi-crystal.html this is in Russian, but Google translate does a good job on something that's very clearly structured and written. If I have a go, I'll write it up.

**Comment by ryanprior** [comment]
I know crystal has come a long way but still don't know much about building on ARM, so I'm closing this issue as stale. Please feel free to re-open with new info @hbarnard!

**Comment by hbarnard** [comment]
> I know crystal has come a long way but still don't know much about building on ARM, so I'm closing this issue as stale. Please feel free to re-open with new info @hbarnard!

No problem, in fact this lay forgotten in my _pile of stuff_. Thanks for reminding me, I have a Pi project for a uni underway, so I may take time off to take another run at this. Thanks for all your work, meanwhile.
