### ISSUE TITLE
secureID flag

### ISSUE THREAD

**Issue by Ottermanns** [ryanprior/meet#3]
Fantastic tool. Have been looking for something like this for a long time. The electron app is not a good alternative. As I need a lot of fixed links (like "meet.jit.si/regularmeeting") I would suggest an additional flag to disable the use of a secureID. Up to now I fixed it by changing line 150 to "link = "https://#{base_url}/#{title_text}".

**Comment by ryanprior** [comment]
Fixed in [1.2.0](https://github.com/ryanprior/meet/releases/tag/1.2.0)

Thank you!

**Comment by Ottermanns** [comment]
Very cool. Thanks! :-)
